### ISSUE TITLE
 How to change  that training code and run on  gpu？

### ISSUE THREAD

**Issue by xxxgcat** [zx33/APAUNet#1]
Hi, I have done the data preprocessing part. But when training, runtime error occurred.
**Can you share how to change  that code and run on  gpu?**
I'm not very familiar with this part of the code and I tried to run many times but failed.
Thank u so much！

**Comment by zx33** [comment]
Hi,

Our training code is implemented for training on GPU.

So if you have the information of the runtime error looks like?

> One potential place where the runtime error occurs might be 'torch.cuda.amp', we use 'autocast' to accelerate the training process (at 'trainer.py' line 67-76).
> 
> This needs your Pytorch >= 1.6 and relies on GPU with Tensor Core (20xx or newer)
> 
> Maybe you can just replace this with the normal backward process `loss.backward()` rather than `scaler.scale(loss).backward()` to see whether the runtime error still occurrs.

**Comment by xxxgcat** [comment]
Hello, I noticed an error in the 'trainer.py' file, on line 10, the error says that the reference to autocast cannot be found in '_init_.py'

> Hi,
> 
> Our training code is implemented for training on GPU.
> 
> So if you have the information of the runtime error looks like?
> 
> > One potential place where the runtime error occurs might be 'torch.cuda.amp', we use 'autocast' to accelerate the training process (at 'trainer.py' line 67-76).
> > This needs your Pytorch >= 1.6 and relies on GPU with Tensor Core (20xx or newer)
> > Maybe you can just replace this with the normal backward process `loss.backward()` rather than `scaler.scale(loss).backward()` to see whether the runtime error still occurrs.

**Hello, I noticed an error in the 'trainer.py' file, on line 10, the error says that the reference to autocast cannot be found in '_init_.py'**

**Comment by zx33** [comment]
Hi,

Since the code is running normally in my environment, I'm not sure what does this 'init.py' refer to or where the error occurs.
It looks like the major issue is about 'torch.cuda.amp'.

So how about discard the 'amp' part, just like I posted above?

Comment:
```
from torch.cuda.amp import autocast, GradScaler
...
with autocast():
...
scaler.scale(loss).backward()
scaler.step(self.optimizer)
scaler.update()
```

Replace with the normal backward codes:
```
...
loss = self.criterion(outputs, targets)
loss.backward()
self.optimizer.step()
```

You can try this to see if the normal training process works properly?

**Comment by xxxgcat** [comment]
**This is the detailed  information of the  runtimeerror, in fact the gpu is not in use.**
![1667656878524](https://user-images.githubusercontent.com/95564137/200123675-5221216e-76c7-4882-8458-dd7788722344.png)
![1667656896428](https://user-images.githubusercontent.com/95564137/200123682-1bed6407-0df6-47b9-992b-f4f74b17b0f7.png)
**Here is my pytorch version**
![3f46ac4733cd5dcb85bc8195683fc82](https://user-images.githubusercontent.com/95564137/200123759-d036d2d8-1a13-4437-b65d-8a49b6e76815.png)

**Comment by zx33** [comment]
😂Hi, the log output shows that your GPU memory is not enough (CUDA out of memory)

Maybe you should use a smaller crop size ($96 \times 96 \times 96$ -> $64 \times 64 \times 64$) in 'config.py' or change to a GPU with larger memory.

**Comment by xxxgcat** [comment]
Well，Thanks for your kind reply.Apparently I made a careless mistake ,I thought that the 3090 would not have the problem of insufficient v memory, so I didn't check it. Thanks！

**Comment by xxxgcat** [comment]
> 😂Hi, the log output shows that your GPU memory is not enough (CUDA out of memory)
> 
> Maybe you should use a smaller crop size ( 96×96×96 -> 64×64×64 ) in 'config.py' or change to a GPU with larger memory.

Well，Thanks for your kind reply.Apparently I made a careless mistake ,I thought that the 3090 would not have the problem of insufficient memory, so I didn't check it. Thanks！😂

**Comment by zx33** [comment]
That's all right, hope this repository helps you, *^____^*

**Comment by xxxgcat** [comment]
Hi, I am trying to use the dataset you mentioned, Can you share the **config** settings for **MSDtask007** and the **BTCV dataset**？
Thank you.

**Comment by zx33** [comment]
Hello, 

All the training and testing hyper-parameters of MSD are set in 'config.py'. You can also modify it according to your own situation.

For BTCV, we are following the settings of nnFormer, you can refer to the github repository of nnFormer.

**Comment by xxxgcat** [comment]
![1667787852408](https://user-images.githubusercontent.com/95564137/200213693-227a6b43-7461-4ae9-8990-50637696c6c4.png)
Thanks for your reply, it looks like the program is training.
Since you are using single GPU training, mine is multi-GPU training, so I have some trouble.
Looks like there is a little problem with dice score though, I will check further.

**Comment by xxxgcat** [comment]
Hello, sorry to bother you again after a few days.
I still can't solve the problem of changing .cuda() to run on multiple GPUs.
Specifically, according to the online tutorial, I changed a part of the code content of "train.py" and "trainer.py".
 In "train.py，I used nn.dataparallel. 
![1668151747109](https://user-images.githubusercontent.com/95564137/201289239-11843dfb-ed4b-40a0-9cd4-22062b8ee1b9.png)
![1668151776378](https://user-images.githubusercontent.com/95564137/201290395-40a1c2f9-8a6d-41ec-a31d-46b48e49ecba.png)
In“trainer.py”，I changed the code with the number of lines as shown.
![1668151763657](https://user-images.githubusercontent.com/95564137/201289730-695c1f7f-94d4-409f-bb60-8fcf4dad3f4a.png)
![1668151833664](https://user-images.githubusercontent.com/95564137/201290536-3e5710b9-6d9b-4d85-a951-5a19f4e4978e.png)


But I still couldn't get the correct dice score, which I was very troubled by.
Don't know if you have a solution?
I would be very grateful if you could provide some help solving the code for changing single GPU training to multi GPU training.

**Comment by zx33** [comment]
'nn.DataParallel' should be a feasible multi-card solution.
What your batch size right now?
If you set the `batch size=2` with 2 GPUs, the `Batchnorm` will not work correctly, since there is only 1 sample on each GPU under the default implementation of `Batchnorm`.
```
# pseudo-code
def batchnorm(x):
    mu = mean(x)
    sigma = std(x)
    x = (x - mu) / sigma
#if batch size = 1, sigma=0.
```
Maybe you may change it to `SyncBatchnorm`.

**Comment by zx33** [comment]
Or you can use `checkpoint` to temporarily save intermediate variables to save GPU memory to ensure that each GPU has batch size larger than 2.
