### ISSUE TITLE
Inference issue

### ISSUE THREAD

**Issue by hogmeade** [zx33/APAUNet#2]
I did the inference on the raw original images and the prediction mask is off from the truth segmentation. Were the model trained on the cropped images? how can we get the cropped original image to match with the predicted mask?
Will the patch size 32_32_32 work?

**Comment by zx33** [comment]
Yes, we did train on the cropped images, and inference on the raw image with `sliding_window_inference`.
We post the inference code in the `inference.py`. After inference you will get a ITK style file and you can use ITK-Snap to simultaneously show the raw image and mask (as the visualization in paper).

About the patch size of 32_32_32, since the model is trained on 96_96_96, the result will not be that good. You can try to train the model with input patch of 32_32_32 to see the results. (according to our experience, if the patch size is too small, it will affect the performance, generally not smaller than 64)

**Comment by hogmeade** [comment]
Thank you for your response. I tried to reproduce the result with the pancreas dataset with the same settings but so far not successfully. I must have done something wrong. So I have a few questions:
1. In train.py - line 22 - trained on **nnUNetData_plans_v2.1_stage0**. Are these the cropped images that you mentioned before? or should I use the folder **nnUNet_cropped_data** instead? what packages do you use to display files in nnUNetData_plans_v2.1_stage0?
2. You mentioned that the model trained on the cropped images but we can do inference on the raw images. Why does the size/dimensions difference between the cropped and original image not matter?
3. Do we have pretrained model for the Task07 Pancreas dataset?
 Thank you for your time.

**Comment by hogmeade** [comment]
Hi, after running the inference, I noticed that the axes of the predicted segmentation are changed.
Using ITK_Snap to load the volume first and then the predicted segmentation, it shows the dimensions mismatched. For example, the volume has dimensions of (512, 512, 90) but the segmentation has dimensions of (90, 512, 512). This issue is from the Write function in the inference file that permute the order. How could you get the volume and predicted segmentation aligned and view them in ITK_SNAP?

**Comment by Oliver-jiang** [comment]
Hi, we use the preprocessed/Task_xxx/nnUNetData_plans_v2.1_stage0 as the train and val dataset. During training and validation, the images are cropped; During inference, images are keep the raw size and use "sliding window inference" with window size 96 for  generating predict results. Aftering inferring, you should permute the channel to fit the order of ITK_SNAP.

**Comment by hogmeade** [comment]
For Pancrease dataset, seems like the issues originating from training on the "nnUNetData_plans_v2.1_stage0" (low resolution) by default in the train.py and do inference on the original high resolution images. Should we train it on the nnUNetData_plans_v2.1_stage1 instead and do inference normally?

**Comment by Oliver-jiang** [comment]
We tried stage0 and stage1 both and got similar results. You can try it to see if this can solve the issue. The error seem to be caused by the corruption of zip file on your side, you should re-generate these files.
